apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-db-password-external-secret
spec:
  refreshInterval: 1h

  secretStoreRef: # refer to secret store 
    name: aws-secret-store
    kind: ClusterSecretStore

  # 
  target:
    name: mysql-secret # name of the secret inside k8s will be created 
    creationPolicy: Owner # to be able to delete secret when external secret deleted
  data:
    - secretKey: mysql-root-password # name of value inside k8s secret 
      remoteRef:
        key: mysql-secret-devops-app # name of secret in aws secret manager
        property: rootPassword # name of property in aws secret manager
    - secretKey: mysql-password
      remoteRef:
        key: mysql-secret-devops-app # name of secret in aws secret manager
        property: password # name of property in aws secret manager