
# # this override default values in postgresql chart
# # but this not related to bitname/postgres chart default values 
# # because  postgresql is dependency chart so when do enabled: false it will not install the subchart 
# mysql: # this attribute are waiting for postgresql chart need him to start your bitname/postgres chart 
#   enabled: false # disable postgresql chart on production environment will use RDS 

# ################## end of postgresql ################

# global:

#   db_host: "terraform-20260728001057683400000004.c52e88koezpq.eu-north-1.rds.amazonaws.com"

#   backend_host: "back-svc" # set in svc of backend chart and use it in frontend chart

#   ################### end of backend ################


#   frontend_host: "front-svc"





# this override default values in postgresql chart
mysql: # this attribute are waiting for postgresql chart need him to start your bitname/postgres chart 
  enabled: true # enable the subchart in dev environment, false to disable it in prod and rely on rds
  auth:
    username: "infra_app"
    database: "infra_platform"
    # rootPassword: "changeme-root"
    # password: "changeme-app"
    existingSecret: "mysql-secret" # get password & postgres-password from secret created by external secret
  primary:
    persistence:
      enabled: true
      storageClass: gp2
      size: 8Gi
################ end of mysql ################

back-chart:
  image:
    repository: "997206200726.dkr.ecr.eu-north-1.amazonaws.com/gp-back"
    tag: "dev-a0b93cd0"
front-chart:
  image:
    repository: "997206200726.dkr.ecr.eu-north-1.amazonaws.com/gp-front"
    tag: "dev-a0b93cd0"
global:
  db_host: "mysql-svc"
  backend_host: "back-svc"
  frontend_host: "front-svc"
  hostname: "devops-app.mycloudlab.website"
