apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-credentials-external-secret
spec:
  refreshInterval: 1h

  secretStoreRef: # refer to secret store 
    name: aws-secret-store
    kind: ClusterSecretStore

  # 
  target:
    name: backend-credentials-secret # name of the secret inside k8s will be created 
    creationPolicy: Owner # to be able to delete secret when external secret deleted
  data:
    - secretKey: DB_PASSWORD # name of value inside k8s secret 
      remoteRef:
        key: backend-devops-app-secret # name of secret in aws secret manager
        property: DB_PASSWORD # name of property in aws secret manager
    - secretKey: JWT_ACCESS_SECRET
      remoteRef:
        key: backend-devops-app-secret # name of secret in aws secret manager
        property: JWT_ACCESS_SECRET # name of property in aws secret manager
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: backend-devops-app-secret # name of secret in aws secret manager
        property: ENCRYPTION_KEY # name of property in aws secret manager

    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: backend-devops-app-secret # name of secret in aws secret manager
        property: ANTHROPIC_API_KEY # name of property in aws secret manager